spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/springcampus?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#jpa hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=237107042277-vs0bijt7a97q619piikiocgaqm4bghr3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google